# Generated by Django 4.0.6 on 2022-07-25 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ariza', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ariza',
            name='amount',
            field=models.BigIntegerField(verbose_name='Homiylik miqdori'),
        ),
        migrations.AlterField(
            model_name='ariza',
            name='fish',
            field=models.CharField(max_length=255, verbose_name='Ism Familya'),
        ),
        migrations.AlterField(
            model_name='ariza',
            name='paymentType',
            field=models.CharField(choices=[('cash', 'Cash'), ('exchange', 'Exchange'), ('None', 'None')], default='None', max_length=35, verbose_name="To'lov turi"),
        ),
        migrations.AlterField(
            model_name='ariza',
            name='phone',
            field=models.CharField(max_length=25, verbose_name='Telefon raqam'),
        ),
        migrations.AlterField(
            model_name='ariza',
            name='status',
            field=models.CharField(choices=[('yangi', 'Yangi'), ('moderatsiya', 'Moderatsiya'), ('tasdiqlangan', 'Tasdiqlangan'), ('cancel', 'Cancel')], default='yangi', max_length=125, verbose_name='Ariza holati'),
        ),
        migrations.AlterField(
            model_name='ariza',
            name='tashkilot',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tashkilot nomi'),
        ),
        migrations.AlterField(
            model_name='ariza',
            name='type',
            field=models.CharField(choices=[('Yuridik', 'Yuridik'), ('jismoniy', 'Jismoniy')], max_length=255, verbose_name='Arizaning turi'),
        ),
    ]
